---
#Service (svc)
apiVersion: v1
kind: Service
metadata:
  name: svc-crud-clientes
  namespace: app-teste
spec:
  type: ClusterIP #NodePort, ClusterIP 
  ports:
    - port: 9000
      # nodePort: 30001
  selector:
    app: crud-clientes

---
# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-crud-clientes
  namespace: app-teste
  annotations:
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/ssl-redirect: "false"
    # traefik.ingress.kubernetes.io/router.tls: "true"
    # traefik.ingress.kubernetes.io/router.tls.certresolver: default
spec:
  rules:
    - host: app-homolog.ddns.net
      http:
        paths:
          - backend:
              service:
                name: svc-crud-clientes
                port:
                  number: 9000
            path: /
            pathType: Prefix

---
#Hpa
# Necessary to install metrics-server https://github.com/kubernetes-sigs/metrics-server
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: crud-clientes-hpa
  namespace: app-teste
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: crud-clientes-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
#  metrics:
#    - type: Resource
#      resource:
#        name: cpu
#        target:
#          type: Utilization
#          averageUtilization: 80

---
# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: crud-clientes-configmap
  namespace: app-teste
data:
  APP_NAME: "crud-clientes"
  APP_ENV: "homolog"
  APP_DEBUG: "true"
  APP_KEY: "base64:0JLDfs7LwMILehN+urNGdtdmuM5KuD7VzRhimKnOll8="
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_USERNAME: "root"
  DB_PASSWORD: "root"
  DB_DATABASE: "crud_cliente"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-clientes-deployment
  namespace: app-teste
spec:
  replicas: 2
  template:
    metadata:
      name: crud-clientes
      labels:
        app: crud-clientes
        access: "true"
    spec:
      containers:
        - name: crud-clientes-container
          image: handersonsilva/crud-clientes:1.1.0
          ports:
            - containerPort: 9000
          resources:
            limits:
              cpu: 200m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 512Mi
          envFrom:
            - configMapRef:
                name: crud-clientes-configmap
          livenessProbe:
            httpGet:
              path: /
              port: 9000
            periodSeconds: 30
            failureThreshold: 4
            initialDelaySeconds: 30
#          readinessProbe:
#            httpGet:
#              path: /
#              port: 9000
#            periodSeconds: 10
#            failureThreshold: 5
#            initialDelaySeconds: 3
  selector:
    matchLabels:
      app: crud-clientes
