apiVersion: v1
kind: ConfigMap
metadata:
  name: crud-clientes-configmap
  namespace: app-teste
data:
  APP_NAME: "crud-clientes"
  APP_ENV: "homolog"
  APP_DEBUG: "true"
  APP_KEY: "base64:0JLDfs7LwMILehN+urNGdtdmuM5KuD7VzRhimKnOll8="
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_USERNAME: "root"
  DB_PASSWORD: "root"
  DB_DATABASE: "crud_cliente"