apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: crud-clientes-hpa
  namespace: app-teste
  labels:
    app: crud-clientes
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: crud-clientes-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80